# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-22 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0003_auto_20170722_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acortar',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
